### PR TITLE
Validate repository URL eagerly

### LINKED ISSUE #197: Validate repository URLs and warn about and ignore bad repositories
Currently bad URLs will _probably_ fail in `get_repo_metadata` when the URL is used for the first time.

That method currently has an `expect` with an empty string.

This issue contains two parts:
1) Validate each repository URL once as soon as it is downloads the list of repositories (see `cannot_be_a_base` among other things)
2) Just for completeness sake change the "expect" message to mention that/whay this can't fail

### PR DESCRIPTION
**Pull request by siegfriedweber**
The validation of the repository URL is already performed when a `StackableRepoProvider` is created and not only when the repository content is requested.

Fixes #197 

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

### CODE REVIEW

File: src/provider/repository/stackablerepository.rs [hunk 1]
```diff
@@ -256,8 +294,8 @@ mod tests {
         let converted_repo = StackableRepoProvider::try_from(&test_repo_crd).unwrap();
         assert_eq!(converted_repo.name, "test");
         assert_eq!(
-            converted_repo.base_url.as_str(),
-            "http://monitoring.stackable.demo:8000/"
+            converted_repo.metadata_url.as_str(),
+            "http://monitoring.stackable.demo:8000/metadata.json"
```
Comment (soenkeliebau) [inline src/provider/repository/stackablerepository.rs:298]: Comment not related to this line, but closest I could get. 
Should we maybe also add a test to check if try_into properly returns an error for a url that cannot be a base. Currently the tests only cover that new(..) returns an error.

**Review by soenkeliebau — APPROVED** [review]
LGTM - just one optional comment

File: src/provider/repository/stackablerepository.rs (hunk 1 above)
Comment (siegfriedweber) [reply src/provider/repository/stackablerepository.rs:298]: In my opinion, unit tests should be white box tests. So the unit test knows that the `try_from` function creates a `StackableRepoProvider` with the already tested `new` function. It is therefore sufficient to only test that the `try_from` function is able to extract the necessary data from the given `Repository` and calls `StackableRepoProvider::new` properly. Replicating the test condition from the other unit test would also not increase the test coverage. The best solution would be to hide the option from the `try_from` function to create a `StackableRepoProvider` without calling the `new` function but that is not possible within one module.
