### PR TITLE
Move restart policy to systemd

### LINKED ISSUE #207: Move restart behavior of services from agent to systemd
As of #205 we default the `RestartOn` setting for our systemd units to `No` to avoid undefined behavior when systemd as well as the agent try to restart a failed unit.

This is not ideal for a couple of reasons and we would like to change this so that systemd is in charge of watching over services and restarting them as needed.

There are a couple of additional settings that we need to add to our units, including, but not limited to: 
- StartLimitBurst
- StartLimitIntervalSec

More detail:
https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6

### PR DESCRIPTION
**Pull request by siegfriedweber**
## Description

Fixes #207
Tested by stackabletech/agent-integration-tests#61

### Changed
* Handling of service restarts moved from the Stackable agent to systemd.

### Removed
* Check removed if a service starts up correctly within 10 seconds. systemd manages restarts now and the Stackable agent cannot detect if a service is in a restart loop.

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

### CODE REVIEW

File: src/provider/states/pod/running.rs [hunk 1]
```diff
@@ -66,7 +64,7 @@ impl State<PodState> for Running {
         // Interruption of this loop is triggered externally by the Krustlet code when
         //   - the pod which this state machine refers to gets deleted
         //   - Krustlet shuts down
-        while !running_containers.is_empty() && !container_failed {
+        while !running_containers.is_empty() {
```
Comment (soenkeliebau) [inline src/provider/states/pod/running.rs:67]: I don't think we fully support multiple containers per pod yet, but in case we do that, my understanding is that this would consider the pod "running" until the last container has exited, is that right?
If so, is that what we want, or would we rather want to fail the pod when even a single container is crashed / exited unsuccessfully? Not sure how Kubernetes handles it tbh..

File: src/provider/systemdmanager/service.rs [hunk 2]
```diff
@@ -49,34 +63,60 @@ impl SystemdService {
...
-                    self.file,
-                    error
-                )
-            })
+    /// Returns a coarse-grained state of the service unit object.
+    ///
+    /// It is assumed that RemainAfterExit is set to "yes" in the given
+    /// unit if the service can terminate. Otherwise it would not be
+    /// possible to distinguish between "inactive and never run" and
+    /// "inactive and terminated successfully".
```
Comment (soenkeliebau) [inline src/provider/systemdmanager/service.rs:71]: Do we need to consider how a server restart would affect this?
I assume that after a server restart we cannot see the unit anymore?

**Review by soenkeliebau — COMMENTED** [review]
LGTM overall, I've left a few questions that I'd like to clarify, but most of those will probably simply be resolveable.

As far as I can tell this would not notice if a service enters into a permanent restart loop, right? It would update the restart count on the pod, but never set a failed condition or something similar?

**Review by razvan — DISMISSED** [review]
I didn't look closely at the code but the corresponding integration tests are green.

File: src/provider/states/pod/starting.rs [hunk 3]
```diff
@@ -72,32 +64,19 @@ async fn start_service_units(
...
-        if systemd_service.is_running().await? {
-            debug!(
-                "Unit [{}] for service [{}] is already running. Skip startup.",
-                systemd_service.file(),
-                &pod_state.service_name
-            );
-        } else {
-            let service_unit = &container_handle.service_unit;
-
+        if systemd_service.service_state().await? == ServiceState::Created {
```
[the remark this answers is not in the document]
Comment (siegfriedweber) [reply src/provider/states/pod/starting.rs:69]: This condition is not met in a restart loop.

`ServiceState::Created` means that the service was created but never started. When the service is started then `systemd_service.service_state()` returns `ServiceState::Started`. It will not leave this state until it is terminated (forever) and it will never return to `ServiceState::Created`. So whatever happens while restarting, `systemd_service.service_state()` always returns `ServiceState::Started`.

File: src/provider/states/pod/running.rs [hunk 4]
```diff
@@ -132,29 +130,38 @@ impl State<PodState> for Running {
...
-            container_failed = !failed_containers.is_empty();
-        }
 
-        if container_failed {
-            if restart_policy(&pod) == RestartPolicy::Never {
-                Transition::next(self, Terminated { successful: false })
-            } else {
-                debug!("Restart policy is set to restart, starting...");
-                Transition::next(self, Starting {})
+                match container_handle.systemd_service.restart_count().await {
```
[the remark this answers is not in the document]
Comment (siegfriedweber) [reply src/provider/states/pod/running.rs:143]: Yes, the restart count is patched every 10 seconds even if it has not changed. I will improve this.

Originally I planned to implement #182 next and replace the loop with dbus signals but the issue was prioritized down.

File: src/provider/states/pod/running.rs (hunk 1 above)
Comment (siegfriedweber) [reply src/provider/states/pod/running.rs:67]: The [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase) defines the pod phase "Running" as "The Pod has been bound to a node, and all of the containers have been created. At least one container is still running, or is in the process of starting or restarting." The pod phase "Failed" is defined as "All containers in the Pod have terminated, and at least one container has terminated in failure. That is, the container either exited with non-zero status or was terminated by the system." It is not mentioned that the state of one container can affect other containers.

I would not terminate the pod if one container failed.

It must also be considered that this condition is only relevant for jobs which can terminate. Services are restarted by systemd if they terminate and are never removed from `running_containers`.

File: src/provider/systemdmanager/service.rs (hunk 2 above)
Comment (siegfriedweber) [reply src/provider/systemdmanager/service.rs:71]: I tested it and a unit which was in state `active (exited)`, was in state `inactive (dead)` after a reboot. So if the machine is rebooted after a job terminated but before the Stackable Agent had the chance to delete it then we have an undesirable state. I will think about it if this problem can be solved.

**Comment by siegfriedweber** [comment]
> As far as I can tell this would not notice if a service enters into a permanent restart loop, right? It would update the restart count on the pod, but never set a failed condition or something similar?

Right. If the restart policy of the pod is set to `Always` or `OnFailure` then this is the desired behavior, I think. The Stackable Agent also does not have a notion what a "restart loop" is. We regard a restart every 10 seconds as a restart loop but a restart every 10 minutes probably not.

File: src/provider/states/pod/running.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (soenkeliebau) [reply src/provider/states/pod/running.rs:143]: Ok, lets wait for 3 then. No use creating extra effort now that we already know will be obsolete soon.

File: src/provider/states/pod/running.rs (hunk 1 above)
Comment (soenkeliebau) [reply src/provider/states/pod/running.rs:67]: Sounds like we adhere to K8s defaults then, which is fine for me.

**Review by soenkeliebau — DISMISSED** [review]
LGTM

**Review by lfrancke — APPROVED** [review]
