### PR TITLE
Synchronize pod state with systemd service state

### LINKED ISSUE #136: The agent does not behave correctly when services fail to react to a stop command in time
It seems like the agent does not wait for commands sent to systemd to finish before continuing with subsequent actions. This can cause systemd to react with an error, if a stop command has not finished before a start command is issued.

```
[2021-04-22T15:06:07Z INFO  stackable_agent::provider::states::pod::creating_service] Creating service unit for service default-spark-cluster-default-master
[2021-04-22T15:06:08Z INFO  stackable_agent::provider::states::pod::starting] Starting systemd unit [default-spark-cluster-default-master-spark.service]
[2021-04-22T15:06:08Z ERROR stackable_agent::provider::states::pod::starting] Error occurred starting systemd unit [default-spark-cluster-default-master-spark.service]: [Error starting service [default-spark-cluster-default-master-spark.service]: Transaction for default-spark-cluster-default-master-spark.service/start is destructive (default-spark-cluster-default-master-spark.service has 'stop' job queued, but 'start' is included in transaction).]
[2021-04-22T15:06:08Z ERROR krator::state] Object state machine exited with error. error=Error starting service [default-spark-cluster-default-master-spark.service]: Transaction for default-spark-cluster-default-master-spark.service/start is destructive (default-spark-cluster-default-master-spark.service has 'stop' job queued, but 'start' is included in transaction).
```

We will create an integration test case to reproduce this and make testing a fix easier (see https://github.com/stackabletech/integration-test-repo/issues/3).

### PR DESCRIPTION
**Pull request by siegfriedweber**
Fixes #136

### CODE REVIEW

File: src/provider/systemdmanager/manager.rs [hunk 1]
```diff
@@ -291,12 +298,44 @@ impl SystemdManager {
...
+    /// Runs the given task and waits until the job returned by the task
+    /// is finished.
+    async fn process_job<'a, F, Fut>(&'a self, task: F) -> anyhow::Result<()>
+    where
+        F: Fn(&'a AsyncManagerProxy) -> Fut,
+        Fut: Future<Output = zbus::Result<AsyncJobProxy<'a>>>,
+    {
+        let signals = self
+            .proxy
+            .receive_signal(ManagerSignals::JobRemoved.into())
```
Comment (lfrancke) [inline src/provider/systemdmanager/manager.rs:321]: I've tried looking at the zbus documentation briefly and I can't find any good documentation about what receive_signal does and the whole thing being generated by macros makes it hard to see as well.

Could you please document what's going on in this method?

**Review by lfrancke — CHANGES_REQUESTED** [review]

File: src/provider/systemdmanager/manager.rs (hunk 1 above)
Comment (siegfriedweber) [reply src/provider/systemdmanager/manager.rs:322]: Done. Please have a look if the comments are sufficient.

Comment (lfrancke) [reply src/provider/systemdmanager/manager.rs:322]: Thank you and I'm sorry for not making myself clearer.

I'd have liked documentation like this (obviously in "correct"):

`Systemd sends a JobRemoved signal when bla bla, we need to wait for this signal before we can return a success because otherwise XYZ will happen which will cause the issue #136. If this signal never comes .... bla bla"

Basically describing _why_ you are doing it this way and not in any other way.

Comment (siegfriedweber) [reply src/provider/systemdmanager/manager.rs:333]: I described now shortly the systemd behaviour.

**Review by lfrancke — APPROVED** [review]
